name: tag-check

on:
  workflow_call:
    outputs:
      tag:
        value: ${{ case(startsWith(github.ref, 'refs/heads/'), jobs.tag.tag_head.tag, startsWith(github.ref, 'refs/tags/'), jobs.tag.tag_tag.tag, 'UNKNOWN') }}

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v6
        if: ${{ startsWith(github.ref, 'refs/heads/') }}
        with:
          fetch-tags: true
      - name: latest tag heads
        if: ${{ startsWith(github.ref, 'refs/heads/') }}
        id: tag_head
        run: |
          tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          
          echo "::notice title=Tag:: $tag"
          echo "tag=$tag" >> $GITHUB_OUTPUT
      - name: latest tag tags
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: tag_tag
        env:
          TAG: ${{ github.ref }}
        run: |
          tag=${TAG#refs/tags/}
          
          echo "::notice title=Tag:: $tag"
          echo "tag=$tag" >> $GITHUB_OUTPUT

  tag_check:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-tags: true
      - name: check release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ needs.tag.outputs.tag }}
        run: |
          if gh release view $TAG; then
            echo "::error::The release $TAG already exists"
            exit 0
          fi